### ISSUE TITLE
masterに商品詳細ページをmergeしたら、エラーが発生しました。

### ISSUE THREAD

**Issue by kawasoe-syouta** [kawasoe-syouta/FM_log#15]
# -問題
#### masterに商品詳細ページをmergeしたら、エラーが発生しました。
Qiitaの記事を見て操作したいのですが、よろしいですか？
https://qiita.com/paranishian/items/06d095fca2f6253b7989

**Comment by neibis-zrm** [comment]
全部のmigrationファイルをrollbackさせてから、一度 rails db:reset した方が良いかも

**Comment by kawasoe-syouta** [comment]
承知しました
