### ISSUE TITLE
migrationが未解決なのでmaigrateしなさいという様なエラーが出る

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#21]
生じているエラー
https://gyazo.com/64ee2f432216b0626cf90b55d0e8b63a

聞きたいこと
rails db:migrateを行ってもいいのか？
実行していいのかわからないので質問させてもらいました

**Comment by neibis-zrm** [comment]
今のmigrate:statusにdownが入っているならば適応されていないのでmigrateしてください。

**Comment by tomoki-ito-annyon** [comment]
適用することができました！ありがとうございます！
