### ISSUE TITLE
デプロイ時にエラーが発生します。

### ISSUE THREAD

**Issue by kawasoe-syouta** [kawasoe-syouta/FM_log#25]
## エラー文
Mysql2::Error: Table 'users' already exists

### 試した事
rails db
SHOW TABLES；
drop table users;

EC2環境でも同様に試してみましたが解消せず

rails db:resetをしてみてもうまくいかず
協力お願いします。

**Comment by neibis-zrm** [comment]
参考になるかもしれないです。
https://qiita.com/kinopyyy/items/c22b6ec10db81d788c6c

**Comment by kawasoe-syouta** [comment]
ありがとうございます
