### ISSUE TITLE
rails db:migrateを行いrails sを行うとtopページと合わさって表示されてしまう

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#27]
生じている問題
加藤さんが作成したページと被ってしまっている
https://gyazo.com/c4dbf6aa529f7db57826344dd9b15783
このようになるので一度ロールバックを行い元の状態に戻しました。
戻している状態ですと当たり前ですがmigrateしてくださいと言うエラーが出てきます

解決したいこと
被さらずに表示されるようにしたい
かぶさるってことはrouteの書き方等がおかしいと思うのですがカリキュラム等振り返ってもわからなかったので教えてくださると助かります
routeyacontrollerなどがいまだに理解不足です、すいません。

**Comment by tomoki-ito-annyon** [comment]
画面収録 2020-08-16 16.44.29
こうなるのですがコードの打ち方がおかしいからですか？😓

**Comment by neibis-zrm** [comment]
- 自分の環境で試してみてもヘッダーの部分は被ってないです。rails sを一度再起動してみると良いかも
- headerのロゴが潰れているのは意図したものですか？

**Comment by tomoki-ito-annyon** [comment]
すいませんコメントありがとうございます
昨日解決の方できました消すのを忘れてしまい申し訳ありません。
