### ISSUE TITLE
SyntaxErrorInTemplateのエラーが出てしまう

### ISSUE THREAD

**Issue by Jumpei-Tanikawa** [kawasoe-syouta/FM_log#28]
生じている問題

ビューを表示させたいが（CSSの記述はまだ行っていない）、SyntaxErrorInTemplateが表示されてしまう。
誤字や抜け字、インデントでのエラーではなさそうですが、厳密に何が原因かわかりません。
https://gyazo.com/32335bb98b824f70dfdc191cd569123b
https://gyazo.com/17122c98bfb6589d44ab3f12df212b5a

解決したいこと
正常にフロントを表示させたい。
エラーの原因が知りたいです。

ご確認よろしくお願い致します。

**Comment by neibis-zrm** [comment]
https://gyazo.com/79d29302550911ebdb196d7dff7a0a6c
インデントが入ってないような気がします。

**Comment by Jumpei-Tanikawa** [comment]
確認不足でした。ありがとうございます！
