### ISSUE TITLE
[問題] masterのルーティング設定が壊れた

### ISSUE THREAD

**Issue by neibis-zrm** [kawasoe-syouta/FM_log#29]
# 今実装している所
#27 の確認中
# 生じている問題
- routes.rbに元々記述されていたルート設定がコンフリクトの修正で消えている
- そのままmasterのroutes.rbを修正しようと考えていますがよろしいでしょうか

**Comment by kannna194** [comment]
ぜひ、お願い致します。

**Comment by Jumpei-Tanikawa** [comment]
ありがとうございます。よろしくお願いいたします。

**Comment by neibis-zrm** [comment]
修正しました
