### ISSUE TITLE
[提案] active-hashを使う

### ISSUE THREAD

**Issue by neibis-zrm** [kawasoe-syouta/FM_log#3]
# 今実装している所
各DBモデルの検証
# 生じている問題
- 固定のデータを取り扱う場合に便利なのでactive-hashのgemを入れたい
# 試した内容
- active-hashを別ブランチでテスト
- 都道府県データを作ってidから読めることを確認
- https://gyazo.com/d2e89849bb64bc807275c2a3c6a3ff18

# 参考
- https://qiita.com/Toman1223/items/8633142312bfa886d50b

**Comment by kawasoe-syouta** [comment]
## 承知しました！
丁寧に参考URLありがとうございます！
引き続きよろしくお願いします！

**Comment by kannna194** [comment]
# 確認しました。
便利なgemなので導入しても良いと思います。
ご提案、ありがとうございます。

**Comment by Jumpei-Tanikawa** [comment]
**確認しました。**

上田さん非常に良い提案ありがとうございます。

**Comment by neibis-zrm** [comment]
write-dbdesignブランチに active_hash gemを追加します
