### ISSUE TITLE
date_selectを上手く実装出来ない

### ISSUE THREAD

**Issue by Jumpei-Tanikawa** [kawasoe-syouta/FM_log#31]
生じている問題
date_selectを使用し生年月日を選択出来るようにしたいが、undefined local variable or methodというエラーが出てしまう。
エラー文
https://gyazo.com/03fd62b0a8e6ee4a929516217cce0df6
エディタ
https://gyazo.com/d2f19e4bccf116c1ee7890dab1167ee8
https://gyazo.com/b7a410e52bcc31c0296f24dcba3913dd

解決したいこと
undefined local variable or methodのエラーを解決したい。送り先のカラムのスペルミス等確認済み

参考記事
https://qiita.com/kaorioka09jm/items/671ebb9771d370500ae5

**Comment by neibis-zrm** [comment]
変数fは何処で宣言されていますか？

**Comment by Jumpei-Tanikawa** [comment]
form_forの変数宣言しておりません。
何処でどのようにう変数宣言すれば良いでしょうか。

**Comment by neibis-zrm** [comment]
では、変数formを使っているように見えますがこれはform_forで宣言されてますか？

**Comment by Jumpei-Tanikawa** [comment]
fはform_forのインスタンスだと解釈しておりました。
自分でサーチかけましたがフォームの数宣言が分からずfの変数宣言がどこでどのようにように宣言したらいいのかがわからないので、ご存知でしたら教えていただきたいです。

ちなみに、私は生年月日のカラムのデータ型をdateに変更しましたが上田さんも変更されていますでしょうか？

**Comment by Jumpei-Tanikawa** [comment]
fの変数宣言がformになっていたので統一することで表示することが出来ました。
ありがとうございました。
