### ISSUE TITLE
[質問] Unpermitted parameter: :category の 許可の仕方をご教示ください

### ISSUE THREAD

**Issue by kannna194** [kawasoe-syouta/FM_log#32]
昨日、コンソールからcategory の値を入力すれば、投稿が可能とアドバイスをいただきましたが、ストロングパラメーターの理解が足らず、投稿できておりません。

お忙しいところ大変恐縮ですが、Unpermitted parameter: :category の 許可の仕方をご教示いただけないでしょうか。

**Comment by neibis-zrm** [comment]
test = Category.create(name: "テスト")

**Comment by kannna194** [comment]
メンターさんに伺って、解決することができました。ありがとうございました。
