### ISSUE TITLE
[WIP]商品削除ができるようにしたい 

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#33]
生じている問題
error文　https://i.gyazo.com/f4441a33b6833b8a5fd845d444314303.png
NoMethodError in Items#show
undefined method `id' for nil:NilClassというエラーが出る
エラー文を調べると色々と載っていたのですが理解する事ができず時間をかけてしまっているので質問させてもらいました。

vsコード
https://i.gyazo.com/b037e4fe31c6fa42d9d5e2d977b453b1.png
https://i.gyazo.com/b9d8663eb1cbcf8b568e555b19b712af.png

**Comment by neibis-zrm** [comment]
これはまだ問題が残っていますか？

**Comment by kannna194** [comment]
このようになりました
https://gyazo.com/08c1ca8bb488d2a2787085884d170f47

**Comment by kannna194** [comment]
コンフリクト部分
https://gyazo.com/9868fcdd5524e1cb919dc1f591ea7f96

**Comment by tomoki-ito-annyon** [comment]
すいません消し忘れです申し訳ありません
