### ISSUE TITLE
コミットができなくなりました

### ISSUE THREAD

**Issue by kannna194** [kawasoe-syouta/FM_log#37]
# 生じている問題
コミットしようとするとNewer commits on Remoteエラーが出るようになりました。

https://gyazo.com/c657e76ca317e284578b66b61dfcd442

# 試した内容
Fetchをクリックしてもコミットできませんでした。
git cherry-pickやgit branch <ブランチ名> <コミット>などを実行しましたが、変化はありませんでした。

**Comment by neibis-zrm** [comment]
fetchとかpushが表示される部分がpublish branchになっているからリモートリポジトリと繋がってないのかもしれません。
https://github.com/desktop/desktop/issues/10362

**Comment by neibis-zrm** [comment]
もしかして git branch -u origin/master を実行しましたか？
git branch -u origin/product-list なら良いのですが

**Comment by kannna194** [comment]
ありがとうございます。解決できました。

**Comment by kannna194** [comment]
すみません。git branch -u origin/master を実行しました

**Comment by neibis-zrm** [comment]
今、masterにコミットされたのでproduct-listに設定してください。masterの方はこちらで戻します。

**Comment by kannna194** [comment]
承知しました。申し訳ありません。
