### ISSUE TITLE
削除機能の最中でエラーが出てしまう

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#38]
問題
itemモデルのidが見つからないと言うようなエラー文が出てしまう
https://gyazo.com/c5e7ffdd6ff6c6eec51e2a9fcd86238c  エラー文
コード
https://gyazo.com/f81ba6fc85ae9f66d5877ce92d76a2e0  商品詳細ページ
https://gyazo.com/f17b22e1c3aeb38595e7812430e012b1  コントローラー
https://gyazo.com/cb21b71d15ba3cf38418382fd4bf7942   route
https://gyazo.com/dac5564b60c195fd3a53a21bcee0335c 削除完了を報告するページ

行った内容
コントローラー　ルーティング　ビューに関してのサイト等をみてどこが違っているのかなど確認し試してみたがエラーは治利ませんでした
すいませんがわかる方いましたらお願いいたします
引き続き調べます

仕組み
showページで削除機能を作り削除完了画面に飛びその後トップページに戻るようにしようとしている

**Comment by neibis-zrm** [comment]
どのブランチで作業していますか？

**Comment by tomoki-ito-annyon** [comment]
マスターで行っていましたブランチを変えないといけませんね😓

**Comment by tomoki-ito-annyon** [comment]
> どのブランチで作業していますか？

サーバーサイド商品削除というブランチで作業しています

**Comment by neibis-zrm** [comment]
```
          .deleteArea
            = link_to "投稿を削除", item_path(@items.id), method: :delete
```

```
  def destroy
    @items.destroy
  end
```
