### ISSUE TITLE
新規登録、ユーザー画面をプルリクエスト後コンフリクトが生じたた

### ISSUE THREAD

**Issue by Jumpei-Tanikawa** [kawasoe-syouta/FM_log#40]
起きている問題
１つコンフリクトが生じており、確認したが何故相反しているのかわからず、消していいのかがわかりません。
わかる方いらっしゃいましたら、ご教授願います。

コンフリクト画面
https://gyazo.com/a4c3bfce77ff26701fb341d738d9aa63

**Comment by neibis-zrm** [comment]
これは多分両方とも必要なので両方とも残してください。

**Comment by Jumpei-Tanikawa** [comment]
上田さんありがとうございます。
両方残す形でresolved致しました。
