### ISSUE TITLE
プルリクエストをマージして、マスターをfetchしたらルーティングのエラーが出るようになりました

### ISSUE THREAD

**Issue by Jumpei-Tanikawa** [kawasoe-syouta/FM_log#43]
生じている問題
ルーティングのエラーが出るようになってしまった。
登録ページ、ログインページのLGTMが出たのでマスターにマージ。
マスターを変更してfetchし変更を反映させるためマイグレーションを行い、bundle install、更にyarnのインストールの指示が出たので、インストールしたがルーティングエラーが出てしまう。

調べた内容
マスターにマージ、fetchするまでは表示されていたので、変更が反映されたことによって生じていると考えられる。
該当するものが見つからずエラーが解決できません。
お忙しい中申し訳ありませんが、お力添えいただけたらと思います。
エラー画面
https://gyazo.com/1409d43d8bcde9c9abadf94139f66a18
ルーティングコード
https://gyazo.com/819e9f97a3e6a82a27fa69324928eb16
フェッチ以外の変更
https://gyazo.com/908ada8f2490be099f3c210564dad00a

**Comment by neibis-zrm** [comment]
コミット番号の6b5e9e1で行ったマージでuserモデルが消えているようです。
