### ISSUE TITLE
コンフリクト解消について

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#49]
生じている問題
https://gyazo.com/b3bb88be8f22b0723a03adb57ad64c9d
itemsコントローラー側は現在の現在の変更を取り込むでいいと思っているのですが、
routes側は両方取り込めばよろしいでしょうか？
お願いいたします

**Comment by neibis-zrm** [comment]
routes側は
1.両方取り込む
2.被っているrootとdevise_forの記述の片方を消す
3.itemsは古い方を消す
4.コメントアウトを消す

コントローラ側は現在の変更で大丈夫だと思います。

**Comment by tomoki-ito-annyon** [comment]
私用でで席外していました今確認いたしましたので行わさせてもらいます！！

**Comment by tomoki-ito-annyon** [comment]
https://gyazo.com/4dc1a7c64b15469887792722bcc2a4e3
こちらの root to: 'items#index'か root 'items#index'はどっちを削除すれば良いでしょうか

**Comment by neibis-zrm** [comment]
機能は同じなので、どっちでも良いです。

**Comment by tomoki-ito-annyon** [comment]
かしこまりましたありがとうございます！コンフリクト解消後コードレビューの方送らせてもらいます。

**Comment by tomoki-ito-annyon** [comment]
https://gyazo.com/0ca0186379fc01a24ea37a62ff381220
何度も申し訳ありません
画像の内容全てコミットしてしまって大丈夫なのでしょうか？
