### ISSUE TITLE
SyntaxError 解消にご協力いただけたら幸いです

### ISSUE THREAD

**Issue by kannna194** [kawasoe-syouta/FM_log#5]
力不足で申し訳ございません。
不備をご指摘いただけたら、幸いです。
よろしくお願い致します。

# 今実装しているところ
トップページのheader
ブランチ名：front_topview

# 生じている問題
-問題1　SyntaxErrorInTemplate in ItemsController#index

# 試した内容
-誤字、脱字、インデントの位置の確認

**Comment by kawasoe-syouta** [comment]
## -問題1
調べてみたところ、formの記述がいくつか間違っていました。
追加で、idを設定するときに文字列の場合は""で囲めていませんでした。
idの部分は修正しました。
編集後のコードは、リモートリポジトリに上げておきました。
### 参考になればと、コードをかいてみました。
headerのみコーディングをしてみましたが、不具合があったら教えてください。
JavaScriptの実装はしていません。

**Comment by kannna194** [comment]
## ご指摘ありがとうございました。
formは、form_withで書かなければいけないという、謎の固定概念があったので、理解しきれないまま書いておりました。
修正案のご提示ありがとうございます。
参考にして修正したところ、無事に表示することができました。
ご協力、ありがとうございました。
