### ISSUE TITLE
ウィザード形式で住所の画面を作成するにあたり、ビューが表示できない

### ISSUE THREAD

**Issue by Jumpei-Tanikawa** [kawasoe-syouta/FM_log#52]
生じている問題
ウィザード形式で新たにrails g devise:controllers usersコマンドを入力し、ウィザード形式用にコントローラー作成、viewのdeviseのregistrationsの中にnew_streets.html.hamlディレクトリを作成しビューの編集を試みたが、うまく表示されない
ルーティングの記述をカリキュラムを見ながら行ったが、上手くいかない

エラー画面
https://gyazo.com/ee1f5f8a7459cbca5033a6dba0e73071
エディタ
https://gyazo.com/2b8d50213ea330604044c72cb68b3652

**Comment by neibis-zrm** [comment]
routingは既にmasterに設定したので作業ブランチをrebaseしてください。

**Comment by Jumpei-Tanikawa** [comment]
ご回答ありがとうございます。
masteにてrebaseし、routingを取り込みましたが、同じエラーが出てしますですが、URLの入力が間違っているのでしょうか。
create_streets.html.hamlもnew_streets.html.hamlも同じくエラーが出ます。
