### ISSUE TITLE
[質問] 商品購入ページの記載内容

### ISSUE THREAD

**Issue by neibis-zrm** [kawasoe-syouta/FM_log#53]
# 今実装しているところ
- 商品購入ページのビューとモデルの参照

# 生じている問題
https://gyazo.com/1a80e69fd6b3b41c931fa5ad48409691
- ポイントの使用はモデルの設計には無いので実装が出来ない
- 配送先の変更も同様にモデルの設計に無いので実装が出来ない

# 解決案
- 実装できない部分のビューを削除する

**Comment by kannna194** [comment]
実際に使用する予定がない上、モデルの設計にないものであれば、削除してしまっても問題ないと思います。

**Comment by Jumpei-Tanikawa** [comment]
必須の機能ではないので僕も削除して問題ないと思います。

**Comment by tomoki-ito-annyon** [comment]
削除でお願いいたします。

**Comment by neibis-zrm** [comment]
該当部分を削除しました
