### ISSUE TITLE
[質問] routesのコンフリクト解消について

### ISSUE THREAD

**Issue by kannna194** [kawasoe-syouta/FM_log#54]
# 生じている問題
rebaseの後、routesのコンフリクトで迷っています。

# コンフリクト箇所
https://gyazo.com/5c052ecf4b9a0dca25fb55051ff2dde6

# 所見
両方の変更を取り込んだ後、入力側の
  resources :items, only: [:index,:show]
  resources :purchases, only: :index
を削除すれば良いと考えておりますが、誤りであれば、ご指摘をいただきたいです。

**Comment by tomoki-ito-annyon** [comment]
問題ないと思います。

**Comment by neibis-zrm** [comment]
```
  resources :items, only: [:index,:show, :destroy] do
    resource :purchases, only: [:show, :update]
    member do
      get "show_image"
    end
  end
```
:itemが被ってるんで纏めてみましたが、これはちょっと動作検証が必要ですね。。

**Comment by kannna194** [comment]
member do end の別の書き方として、HTTPメソッド名 'アクション名', :on => :memberの書き方があったので、
下記のように書き直しをしたら、表示されました。

```
  resources :items, only: [:index,:show, :destroy] do
   get 'show_image', :on => :member
   resource :purchases, only: [:show, :update]
  end
```

ご指摘、ありがとうございました。
