### ISSUE TITLE
[質問]クラス名をつけてCSSを適応させたい

### ISSUE THREAD

**Issue by Jumpei-Tanikawa** [kawasoe-syouta/FM_log#55]
実装しているとこと
住所登録ページ
active_hashを使用した都道府県選択機能実装の装飾

生じている問題
フォームにクラス名をつけても、適応されない
= form.collection_selectのクラス名の設定の仕方が間違っているのだと思うのですが、わかりません

ビュー
https://gyazo.com/5fe0800e2d039ec2a920370b6f361caf
エディタ
https://gyazo.com/01e8fac4f49d050314ff9e29569387d1

ご確認よろしくお願い致します。

**Comment by neibis-zrm** [comment]
cssにStreetPageは定義されていますか？UserPageの中にformatが入っているような気がします。

**Comment by Jumpei-Tanikawa** [comment]
ご確認ありがとうございます。
StreetPageを定義して、装飾しております。
https://gyazo.com/eeae392de7d9fd1c576a2ce64d072a88

**Comment by Jumpei-Tanikawa** [comment]
StreetとUserが混在しておりました。もう一度確認させて頂きます。

**Comment by Jumpei-Tanikawa** [comment]
クラス名を統一しても装飾が施されるクラスとそうでないクラスが発生してしまいます。
https://gyazo.com/4737ee67f63274e984e9f989b460be51

**Comment by neibis-zrm** [comment]
{}を付けて渡さないといけないみたいです
https://qiita.com/ohnitakahiro/items/c536fe65e37980e1087e

**Comment by Jumpei-Tanikawa** [comment]
上田さん、キータ記事わざわざ探してくださりありがとうございました。
確認させて頂きまして、クラス名に{}が必要であると理解し、追加しクラス名を定義しましたが、表示されません。
メンターに確認した方が良さそうですか？

**Comment by neibis-zrm** [comment]
`form.collection_select :prefecture_id, Prefecture.all, :id, :name, {}, {class: "StreetPage__format__text"}`
これはどうですか

**Comment by Jumpei-Tanikawa** [comment]
上田さんありがとうございます！表示されました！
引数の数が違ったみたいですね。勉強になりました。
