### ISSUE TITLE
ログインして試したい事がある

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#58]
質問
商品出品時に登録した情報が見られるようになっていると言う部分を確認したい
そこでログインをしたいのですがguthub desktopでmasterブランチにしてfetch originすれば読み込まれますか？
ログイン、新規登録、と出品する事が今できない状態です

**Comment by kannna194** [comment]
rebaseコマンドを使ってrebaseを行えば、自分の作業ブランチで会員登録ができるようになります。

**Comment by tomoki-ito-annyon** [comment]
自分が今行っているブランチの状態でgit rebase -iこれをターミナルで打ち込む事で会員登録が可能と言う事でしょうか
カリキュラム等読みましたが理解が違っていたらすいません

**Comment by kannna194** [comment]
-iはいらないと思います。
rebaseコマンドについて、私は下記のサイトがわかりやすいと思いました。ご参考程度にご確認ください。

http://sota1235.com/blog/2015/03/19/git-rebase.html

**Comment by tomoki-ito-annyon** [comment]
ありがとうございます
これをみながらやっているのですが次の画像からコミットしていいのかわからないのですが教えていただいてもよろしいでしょうか？

**Comment by tomoki-ito-annyon** [comment]
https://gyazo.com/c5fb8a856f6bd66c41f32dd46d548d2d
