### ISSUE TITLE
[質問]会員登録のビューについて

### ISSUE THREAD

**Issue by kannna194** [kawasoe-syouta/FM_log#59]
試しに会員登録して、少し気になったのでお伺い致します。

sign_upページでは、UserPage__footerの背景色は#f8f8f8で表示されますが、次のusersのページでは、白く表示されます。

sign_upページ
https://gyazo.com/979139ab66957541eefb3791d1027a10
usersページ
https://gyazo.com/4697740041c8a388e866b5b02df511dc

マスターでは試していないので、私のPC限定のバグだったらすみません。

一度、ご確認をお願い致します。

**Comment by neibis-zrm** [comment]
修正箇所を確認しました。次のユーザー登録機能のマージで反映します。

**Comment by kannna194** [comment]
ご対応、ありがとうございます。
よろしくお願い致します。
