### ISSUE TITLE
新規登録の方行ったところエラーが出てしまった

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#62]
生じている問題
https://gyazo.com/c5fb8a856f6bd66c41f32dd46d548d2d
上の図のようなエラーが出てしまう
シークエルプロでもデータが反映されておりませんでした
加藤さんと何がいけないのか探してましたが解けなかったので教えてくださるとありがたいです

**Comment by neibis-zrm** [comment]
それが起きる事は確認していたのですが根本的な原因が分かっていません。以下の事を確認してみてください。
- 既に登録している名前と同じ名前で登録しようとしている
- サーバーを再起動する

**Comment by tomoki-ito-annyon** [comment]
上田さんに言われた通り再起動を行い新規登録する際名前を変えて登録したところ次のエラーが出てしまいました
https://gyazo.com/0442aaad7b2d4ad8f50fdae318ed92fb

**Comment by neibis-zrm** [comment]
migrationを全部ロールバックしてマイグレートする必要がありそうです。

**Comment by tomoki-ito-annyon** [comment]
ロールバックを行いマイグレートを行いサーバー落として再起動し新規登録行いましたが変わらずエラーが出てしまいます
調べてはいますが解決策がピンときていません
https://gyazo.com/bdcfcbc2b2be4e90daa91d2d76762034

**Comment by tomoki-ito-annyon** [comment]
登録画面は成功したのですが次に住所入力の方で登録を押しても反映されないです登録内容に不備があるせいでしょうか？一応不備がないかは確認はいたしました
https://gyazo.com/dfe0876e612a331a0cf07f50b854a505?token=953aff213037e66b22424b1b7404510d

**Comment by neibis-zrm** [comment]
今は住所登録まで行けたらユーザーが入っているのでトップページに戻って大丈夫です

**Comment by tomoki-ito-annyon** [comment]
はい。ありがとうございます！
