### ISSUE TITLE
StandardErrorの解消に御協力いただきたいです。

### ISSUE THREAD

**Issue by kannna194** [kawasoe-syouta/FM_log#63]
プルリクエスト で発生した、コンフリクトを解消したところ、StandardErrorが出るようになりました。

### 解消したコンフリクト
1. routes.brのresources :items, only: [:index,:show, :destroy] doの下に、get 'show_image', :on => :memberを追加。
2. schema.brのActiveRecord::Schema.define(version: 2020_08_12_112101)をActiveRecord::Schema.define(version: 2020_08_24_112101)に変更

以上2点を変更しました。

### 所感
例外処理については、まだ理解が足りていないので誰かご教示いただければ、幸いです。

**Comment by neibis-zrm** [comment]
何をしたら起きましたか？

**Comment by kannna194** [comment]
コンフリクト解消後、ローカルホストを再読み込み→ActiveRecord::PendingMigrationError→「Run pending migrations」をクリック→StandardError
という流れで、発生しています。

**Comment by neibis-zrm** [comment]
多分、一度migrationを全部ロールバックしてマイグレートする必要があるかも。

**Comment by kannna194** [comment]
ご教示ありがとうございました。
全部ロールバックしてマイグレート後、全て正常に機能しました。
ありがとうございます。
