### ISSUE TITLE
カテゴリ機能について

### ISSUE THREAD

**Issue by kawasoe-syouta** [kawasoe-syouta/FM_log#64]
メンターさんにプルリクエストをみていただいたのですが、言われたとうりに修正しようとすると、エラーが起こってしまいます。

@item = Item.find(params[:id])が不要と言われましたが、消すとエラーになってしまいます。
@category = Category.find_by(id: @item.category_id) を@item.categoryに変更すると正しく表示されないです。

解決ご協力お願いします。

**Comment by neibis-zrm** [comment]
items_controller.rb  line 12
`    @category = @items.category `

show.html.haml  line 97
`        - if user_signed_in? && current_user.id == @items.sell_user_id`
