### ISSUE TITLE
if文の定義について

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#67]
問題
出品者以外にしか商品購入のリンクが踏めないようにする事ができず困っています
今の状態ですとログインしている時、削除ボタン＋購入ボタンが表示されている状態です。どのようにすればいいでしょうか？
コード貼らせてもらいます
https://gyazo.com/01f927494b5a20a9850cd1e45f62ece6

**Comment by neibis-zrm** [comment]
buy_user_idは購入したユーザーなのでsell_user_idを使ってください。

**Comment by tomoki-ito-annyon** [comment]
buyからsellに変更いたしました
購入済みの商品にも表示できないようにするに関しては調べておきます！
