### ISSUE TITLE
マイページ画面に出品数の表示が出来ない

### ISSUE THREAD

**Issue by Jumpei-Tanikawa** [kawasoe-syouta/FM_log#68]
生じている問題
マイページにユーザーの出品数を表示したいが、出来ない。
showアクションにて配列を取り込むコードを記述したが表示されません。

エラーコード
https://gyazo.com/c095c6ee36567639877f79787b0b9134
haml
https://gyazo.com/35450377b8ffd2452a5512e580784f8c
コントローラー
https://gyazo.com/64396049eab5f4632c35ff4586baef2d

初歩的な点でで申し訳ありませんが、ご確認よろしくお願い致します。

**Comment by neibis-zrm** [comment]
showアクションに指定したユーザーは登録していますか？

**Comment by Jumpei-Tanikawa** [comment]
指定したユーザーの登録とはどういうことでしょう？
また、beforeアクション内で@itemsを定義する必要等はありますでしょうか

**Comment by neibis-zrm** [comment]
では、どのようなURLを使ってブラウザに表示させようとしましたか？
beforeアクションについてはどちらでも良いと思います。

**Comment by Jumpei-Tanikawa** [comment]
URLはlocalhost:3000/mypages/index　で間ページは表示されます。
