### ISSUE TITLE
rebaseした際のコンフリクトの解消について

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#69]
ブランド側
https://gyazo.com/f6914a27ecf8f81e198d150005f7d7f6
両方取り込むでいいと思っている

カテゴリ側
https://gyazo.com/4e851bf3bc0a020c54f2134c9f667726
こちらも両方取り込むでいいと思っているのですが確認お願いします

**Comment by kannna194** [comment]
ブランド側もカテゴリ側も、両方取り込んでくれないと、悲しくなります。

**Comment by tomoki-ito-annyon** [comment]
はい取り込みますwありがとうございます！

**Comment by tomoki-ito-annyon** [comment]
https://gyazo.com/d4396ecf27221c2c6934f502bf859c12
コミットするとやり直しと書いてあるのですがこのあとどうすれば良いのでしょうか？
ブランチを作業中のブランチに変更すれば完了でしょうか？
