### ISSUE TITLE
[提案]databaseのencordingについて

### ISSUE THREAD

**Issue by neibis-zrm** [kawasoe-syouta/FM_log#7]
# 今実装している所
#6 の検証
# 生じている問題
- database.ymlのencordingをutf8mb4になっているのでstring型のインデックスが対応しない
- utf8に変更したい
# 試した内容
migrateしようとするとSpecified key was too long; max key length is 767 bytesというエラーが発生することを確認
utf8に変更してdbを再作成すると通る

**Comment by tomoki-ito-annyon** [comment]
変更していいと思います

**Comment by kawasoe-syouta** [comment]
utf8への変更に賛成します。

**Comment by kannna194** [comment]
ご提案、ありがとうございます。
変更して良いと思います。

**Comment by neibis-zrm** [comment]
masterでdatabase.ymlを変更します。

**Comment by neibis-zrm** [comment]
と思ったらmasterは既に変更済みだったのでそのままで良さそうです。
