### ISSUE TITLE
[質問]logo.pngなどの画像が正しく表示されなくて困っている

### ISSUE THREAD

**Issue by tomoki-ito-annyon** [kawasoe-syouta/FM_log#8]
生じている問題
= image_tag "/material/logo/logo.png"と記入してもhttps://gyazo.com/cded3563257110c1bb979d83773180bdこの様になる

= image_tag "material/icon/icon-02.png"こちらのコードは反映しています

試した内容
rails sの文の中に、ActionController::RoutingError (No route matches [GET] "/material/logo/png"):という文が出ていたので調べてみた所scssのファイルに.erbを追加しscssの記述を修正してみると書いてあったがscssに.erbを追加っていうのが理解できず行えていないので
= image_tag "/material/logo/logo.png"のこの文のどこかを直せば反映できるならその方法を教えて欲しいです

**Comment by kawasoe-syouta** [comment]
materialの前についている/を消してみてはどうですか？

**Comment by tomoki-ito-annyon** [comment]
今確認してみた所表示することができました！
ありがとうございます。
